<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Movie;
use App\Models\Actor;
use Illuminate\Support\Str;

class PopularMoviesSeeder extends Seeder
{
    public function run()
    {
        $movies = [
            [
                'title' => 'Inception',
                'slug' => 'inception',
                'sub_title' => 'Inception',
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology.',
                'poster' => 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'video_url' => '/videos/inception.mp4',
                'duration' => 148,
                'release_year' => 2010,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 8.8,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    [
                        'name' => 'Leonardo DiCaprio',
                        'slug' => 'leonardo-dicaprio',
                        'biography' => 'Nam diễn viên người Mỹ, nổi tiếng với vai Dom Cobb trong Inception.',
                        'avatar' => 'https://image.tmdb.org/t/p/w500/A85WIRIKVsD2DeUSc8wQ4fOKc4e.jpg',
                        'birth_date' => '1974-11-11',
                        'birth_place' => 'Los Angeles, California, Mỹ',
                        'status' => 1,
                        'character_name' => 'Dom Cobb'
                    ],
                    [
                        'name' => 'Joseph Gordon-Levitt',
                        'slug' => 'joseph-gordon-levitt',
                        'biography' => 'Nam diễn viên người Mỹ, nổi tiếng với vai Arthur trong Inception.',
                        'avatar' => 'https://image.tmdb.org/t/p/w500/4U9G4YwTlIEbH4YyG3J0rT0w3b7.jpg',
                        'birth_date' => '1981-02-17',
                        'birth_place' => 'Los Angeles, California, Mỹ',
                        'status' => 1,
                        'character_name' => 'Arthur'
                    ],
                    [
                        'name' => 'Elliot Page',
                        'slug' => 'elliot-page',
                        'biography' => 'Diễn viên người Canada, nổi tiếng với vai Ariadne trong Inception.',
                        'avatar' => 'https://image.tmdb.org/t/p/w500/caX3KtMU42EP3VmtW43ptwQymlP.jpg',
                        'birth_date' => '1987-02-21',
                        'birth_place' => 'Halifax, Nova Scotia, Canada',
                        'status' => 1,
                        'character_name' => 'Ariadne'
                    ],
                ],
            ],
            [
                'title' => 'The Dark Knight',
                'slug' => 'the-dark-knight',
                'sub_title' => 'The Dark Knight',
                'description' => 'Batman raises the stakes in his war on crime.',
                'poster' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'video_url' => '/videos/darkknight.mp4',
                'duration' => 152,
                'release_year' => 2008,
                'quality' => 'HD',
                'age_rating' => 'T16',
                'imdb_rating' => 9.0,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Christian Bale', 'slug' => 'christian-bale', 'character_name' => 'Bruce Wayne / Batman'],
                    ['name' => 'Heath Ledger', 'slug' => 'heath-ledger', 'character_name' => 'Joker'],
                    ['name' => 'Aaron Eckhart', 'slug' => 'aaron-eckhart', 'character_name' => 'Harvey Dent'],
                ],
            ],
            [
                'title' => 'Forrest Gump',
                'slug' => 'forrest-gump',
                'sub_title' => 'Forrest Gump',
                'description' => 'The presidencies of Kennedy and Johnson, the Vietnam War, and more through the eyes of an Alabama man.',
                'poster' => 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=bLvqoHBptjg',
                'video_url' => '/videos/forrestgump.mp4',
                'duration' => 142,
                'release_year' => 1994,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 8.8,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Tom Hanks', 'slug' => 'tom-hanks', 'character_name' => 'Forrest Gump'],
                    ['name' => 'Robin Wright', 'slug' => 'robin-wright', 'character_name' => 'Jenny Curran'],
                    ['name' => 'Gary Sinise', 'slug' => 'gary-sinise', 'character_name' => 'Lieutenant Dan Taylor'],
                ],
            ],
            [
                'title' => 'The Shawshank Redemption',
                'slug' => 'the-shawshank-redemption',
                'sub_title' => 'The Shawshank Redemption',
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'poster' => 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=6hB3S9bIaco',
                'video_url' => '/videos/shawshank.mp4',
                'duration' => 142,
                'release_year' => 1994,
                'quality' => 'HD',
                'age_rating' => 'T16',
                'imdb_rating' => 9.3,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Tim Robbins', 'slug' => 'tim-robbins', 'character_name' => 'Andy Dufresne'],
                    ['name' => 'Morgan Freeman', 'slug' => 'morgan-freeman', 'character_name' => 'Red'],
                    ['name' => 'Bob Gunton', 'slug' => 'bob-gunton', 'character_name' => 'Warden Norton'],
                ],
            ],
            [
                'title' => 'Fight Club',
                'slug' => 'fight-club',
                'sub_title' => 'Fight Club',
                'description' => 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.',
                'poster' => 'https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/8uO0gUM8aNqYLs1OsTBQiXu0fEv.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=SUXWAEX2jlg',
                'video_url' => '/videos/fightclub.mp4',
                'duration' => 139,
                'release_year' => 1999,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 8.8,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Edward Norton', 'slug' => 'edward-norton', 'character_name' => 'The Narrator'],
                    ['name' => 'Brad Pitt', 'slug' => 'brad-pitt', 'character_name' => 'Tyler Durden'],
                    ['name' => 'Helena Bonham Carter', 'slug' => 'helena-bonham-carter', 'character_name' => 'Marla Singer'],
                ],
            ],
            [
                'title' => 'The Godfather',
                'slug' => 'the-godfather',
                'sub_title' => 'The Godfather',
                'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
                'poster' => 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=sY1S34973zA',
                'video_url' => '/videos/godfather.mp4',
                'duration' => 175,
                'release_year' => 1972,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 9.2,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Marlon Brando', 'slug' => 'marlon-brando', 'character_name' => 'Vito Corleone'],
                    ['name' => 'Al Pacino', 'slug' => 'al-pacino', 'character_name' => 'Michael Corleone'],
                    ['name' => 'James Caan', 'slug' => 'james-caan', 'character_name' => 'Sonny Corleone'],
                ],
            ],
            [
                'title' => 'Joker',
                'slug' => 'joker',
                'sub_title' => 'Joker',
                'description' => 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society.',
                'poster' => 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/4W0FnjSGn4x0mKZlBRx8OjFxQUM.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
                'video_url' => '/videos/joker.mp4',
                'duration' => 122,
                'release_year' => 2019,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 8.4,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Joaquin Phoenix', 'slug' => 'joaquin-phoenix', 'character_name' => 'Arthur Fleck'],
                    ['name' => 'Robert De Niro', 'slug' => 'robert-de-niro', 'character_name' => 'Murray Franklin'],
                    ['name' => 'Zazie Beetz', 'slug' => 'zazie-beetz', 'character_name' => 'Sophie Dumond'],
                ],
            ],
            [
                'title' => 'Pulp Fiction',
                'slug' => 'pulp-fiction',
                'sub_title' => 'Pulp Fiction',
                'description' => 'The lives of two mob hitmen, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
                'poster' => 'https://image.tmdb.org/t/p/w500/dM2w364MScsjFf8pfMbaWUcWrR.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
                'video_url' => '/videos/pulpfiction.mp4',
                'duration' => 154,
                'release_year' => 1994,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 8.9,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'John Travolta', 'slug' => 'john-travolta', 'character_name' => 'Vincent Vega'],
                    ['name' => 'Uma Thurman', 'slug' => 'uma-thurman', 'character_name' => 'Mia Wallace'],
                    ['name' => 'Samuel L. Jackson', 'slug' => 'samuel-l-jackson', 'character_name' => 'Jules Winnfield'],
                ],
            ],
            [
                'title' => 'The Matrix',
                'slug' => 'the-matrix',
                'sub_title' => 'The Matrix',
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
                'poster' => 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/9tgJfqkqj8lQ9yrhUHF1lGd07dF.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
                'video_url' => '/videos/matrix.mp4',
                'duration' => 136,
                'release_year' => 1999,
                'quality' => 'HD',
                'age_rating' => 'T16',
                'imdb_rating' => 8.7,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Keanu Reeves', 'slug' => 'keanu-reeves', 'character_name' => 'Neo'],
                    ['name' => 'Laurence Fishburne', 'slug' => 'laurence-fishburne', 'character_name' => 'Morpheus'],
                    ['name' => 'Carrie-Anne Moss', 'slug' => 'carrie-anne-moss', 'character_name' => 'Trinity'],
                ],
            ],
            [
                'title' => 'The Lord of the Rings: The Return of the King',
                'slug' => 'the-lord-of-the-rings-the-return-of-the-king',
                'sub_title' => 'The Lord of the Rings: The Return of the King',
                'description' => 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
                'poster' => 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=r5X-hFf6Bwo',
                'video_url' => '/videos/lotr-returnoftheking.mp4',
                'duration' => 201,
                'release_year' => 2003,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 9.0,
                'is_series' => 0,
                'total_episodes' => 1,
                'current_episode' => 1,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Elijah Wood', 'slug' => 'elijah-wood', 'character_name' => 'Frodo Baggins'],
                    ['name' => 'Viggo Mortensen', 'slug' => 'viggo-mortensen', 'character_name' => 'Aragorn'],
                    ['name' => 'Ian McKellen', 'slug' => 'ian-mckellen', 'character_name' => 'Gandalf'],
                ],
            ],
        ];

        foreach ($movies as $movieData) {
            $actors = $movieData['actors'];
            unset($movieData['actors']);
            $movie = Movie::updateOrCreate(['slug' => $movieData['slug']], $movieData);
            foreach ($actors as $actorData) {
                $actor = Actor::firstOrCreate(
                    ['slug' => $actorData['slug']],
                    [
                        'name' => $actorData['name'],
                        'biography' => $actorData['biography'] ?? null,
                        'avatar' => $actorData['avatar'] ?? null,
                        'birth_date' => $actorData['birth_date'] ?? null,
                        'birth_place' => $actorData['birth_place'] ?? null,
                        'status' => $actorData['status'] ?? 1,
                    ]
                );
                // Gán diễn viên vào phim với tên nhân vật
                DB::table('movie_actor')->updateOrInsert([
                    'movie_id' => $movie->id,
                    'actor_id' => $actor->id
                ], [
                    'character_name' => $actorData['character_name']
                ]);
            }
        }
    }
} 