<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Movie;
use App\Models\Actor;
use Illuminate\Support\Str;

class FullMoviesSeeder extends Seeder
{
    public function run()
    {
        $movies = [
            [
                'title' => 'Breaking Bad',
                'slug' => 'breaking-bad',
                'sub_title' => 'Breaking Bad',
                'description' => 'A high school chemistry teacher turned methamphetamine manufacturer partners with a former student to secure his family\'s financial future.',
                'poster' => 'https://image.tmdb.org/t/p/w500/3x7uokDcohmWLfgn1WQThfbdd3o.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=HhesaQXLuRY',
                'video_url' => '/videos/breakingbad.mp4',
                'duration' => 45,
                'release_year' => 2008,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 9.5,
                'is_series' => 1,
                'total_episodes' => 62,
                'current_episode' => 62,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Bryan Cranston', 'slug' => 'bryan-cranston', 'character_name' => 'Walter White'],
                    ['name' => 'Aaron Paul', 'slug' => 'aaron-paul', 'character_name' => 'Jesse Pinkman'],
                    ['name' => 'Anna Gunn', 'slug' => 'anna-gunn', 'character_name' => 'Skyler White'],
                ],
            ],
            [
                'title' => 'Game of Thrones',
                'slug' => 'game-of-thrones',
                'sub_title' => 'Game of Thrones',
                'description' => 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
                'poster' => 'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=gcTkNV5Vg1E',
                'video_url' => '/videos/got.mp4',
                'duration' => 60,
                'release_year' => 2011,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 9.3,
                'is_series' => 1,
                'total_episodes' => 73,
                'current_episode' => 73,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Emilia Clarke', 'slug' => 'emilia-clarke', 'character_name' => 'Daenerys Targaryen'],
                    ['name' => 'Kit Harington', 'slug' => 'kit-harington', 'character_name' => 'Jon Snow'],
                    ['name' => 'Peter Dinklage', 'slug' => 'peter-dinklage', 'character_name' => 'Tyrion Lannister'],
                ],
            ],
            [
                'title' => 'Stranger Things',
                'slug' => 'stranger-things',
                'sub_title' => 'Stranger Things',
                'description' => 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
                'poster' => 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=b9EkMc79ZSU',
                'video_url' => '/videos/strangerthings.mp4',
                'duration' => 50,
                'release_year' => 2016,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 8.7,
                'is_series' => 1,
                'total_episodes' => 34,
                'current_episode' => 34,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Millie Bobby Brown', 'slug' => 'millie-bobby-brown', 'character_name' => 'Eleven'],
                    ['name' => 'Finn Wolfhard', 'slug' => 'finn-wolfhard', 'character_name' => 'Mike Wheeler'],
                    ['name' => 'Winona Ryder', 'slug' => 'winona-ryder', 'character_name' => 'Joyce Byers'],
                ],
            ],
            [
                'title' => 'The Crown',
                'slug' => 'the-crown',
                'sub_title' => 'The Crown',
                'description' => 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
                'poster' => 'https://image.tmdb.org/t/p/w500/80D1PxEBQ2byUMvSIHqhqvW1aEq.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/5QKkK6wZWF4bH4dDdrm3z9VkCGV.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=JWtnJjn6ng0',
                'video_url' => '/videos/thecrown.mp4',
                'duration' => 60,
                'release_year' => 2016,
                'quality' => 'HD',
                'age_rating' => 'T16',
                'imdb_rating' => 8.7,
                'is_series' => 1,
                'total_episodes' => 40,
                'current_episode' => 40,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Claire Foy', 'slug' => 'claire-foy', 'character_name' => 'Queen Elizabeth II'],
                    ['name' => 'Matt Smith', 'slug' => 'matt-smith', 'character_name' => 'Prince Philip'],
                    ['name' => 'Olivia Colman', 'slug' => 'olivia-colman', 'character_name' => 'Queen Elizabeth II (Later Seasons)'],
                ],
            ],
            [
                'title' => 'The Mandalorian',
                'slug' => 'the-mandalorian',
                'sub_title' => 'The Mandalorian',
                'description' => 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
                'poster' => 'https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=aOC8E8z_ifw',
                'video_url' => '/videos/mandalorian.mp4',
                'duration' => 40,
                'release_year' => 2019,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 8.7,
                'is_series' => 1,
                'total_episodes' => 16,
                'current_episode' => 16,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Pedro Pascal', 'slug' => 'pedro-pascal', 'character_name' => 'Din Djarin / The Mandalorian'],
                    ['name' => 'Gina Carano', 'slug' => 'gina-carano', 'character_name' => 'Cara Dune'],
                    ['name' => 'Carl Weathers', 'slug' => 'carl-weathers', 'character_name' => 'Greef Karga'],
                ],
            ],
            [
                'title' => 'The Witcher',
                'slug' => 'the-witcher',
                'sub_title' => 'The Witcher',
                'description' => 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
                'poster' => 'https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=ndl1W4ltcmg',
                'video_url' => '/videos/witcher.mp4',
                'duration' => 60,
                'release_year' => 2019,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 8.2,
                'is_series' => 1,
                'total_episodes' => 16,
                'current_episode' => 16,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Henry Cavill', 'slug' => 'henry-cavill', 'character_name' => 'Geralt of Rivia'],
                    ['name' => 'Anya Chalotra', 'slug' => 'anya-chalotra', 'character_name' => 'Yennefer of Vengerberg'],
                    ['name' => 'Freya Allan', 'slug' => 'freya-allan', 'character_name' => 'Ciri'],
                ],
            ],
            [
                'title' => 'The Office',
                'slug' => 'the-office',
                'sub_title' => 'The Office',
                'description' => 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
                'poster' => 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/3x3cqs1xM8tW3sWERBB0-CDhLfm.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=K-mwCQzKfxM',
                'video_url' => '/videos/theoffice.mp4',
                'duration' => 22,
                'release_year' => 2005,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 8.9,
                'is_series' => 1,
                'total_episodes' => 201,
                'current_episode' => 201,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Steve Carell', 'slug' => 'steve-carell', 'character_name' => 'Michael Scott'],
                    ['name' => 'John Krasinski', 'slug' => 'john-krasinski', 'character_name' => 'Jim Halpert'],
                    ['name' => 'Jenna Fischer', 'slug' => 'jenna-fischer', 'character_name' => 'Pam Beesly'],
                ],
            ],
            [
                'title' => 'Friends',
                'slug' => 'friends',
                'sub_title' => 'Friends',
                'description' => 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.',
                'poster' => 'https://image.tmdb.org/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/5kkw5RT1OjTAMh3P5joQfvDnBL1.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=hDNNmeeJs1Q',
                'video_url' => '/videos/friends.mp4',
                'duration' => 22,
                'release_year' => 1994,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 8.9,
                'is_series' => 1,
                'total_episodes' => 236,
                'current_episode' => 236,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Jennifer Aniston', 'slug' => 'jennifer-aniston', 'character_name' => 'Rachel Green'],
                    ['name' => 'Courteney Cox', 'slug' => 'courteney-cox', 'character_name' => 'Monica Geller'],
                    ['name' => 'Lisa Kudrow', 'slug' => 'lisa-kudrow', 'character_name' => 'Phoebe Buffay'],
                ],
            ],
            [
                'title' => 'The Big Bang Theory',
                'slug' => 'the-big-bang-theory',
                'sub_title' => 'The Big Bang Theory',
                'description' => 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.',
                'poster' => 'https://image.tmdb.org/t/p/w500/ooBGRQBdbGzBxAVfExiO8rDkI1h.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/5kkw5RT1OjTAMh3P5joQfvDnBL1.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=WBb3fojgW0Q',
                'video_url' => '/videos/bigbangtheory.mp4',
                'duration' => 22,
                'release_year' => 2007,
                'quality' => 'HD',
                'age_rating' => 'T13',
                'imdb_rating' => 8.1,
                'is_series' => 1,
                'total_episodes' => 279,
                'current_episode' => 279,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Jim Parsons', 'slug' => 'jim-parsons', 'character_name' => 'Sheldon Cooper'],
                    ['name' => 'Kaley Cuoco', 'slug' => 'kaley-cuoco', 'character_name' => 'Penny'],
                    ['name' => 'Johnny Galecki', 'slug' => 'johnny-galecki', 'character_name' => 'Leonard Hofstadter'],
                ],
            ],
            [
                'title' => 'The Walking Dead',
                'slug' => 'the-walking-dead',
                'sub_title' => 'The Walking Dead',
                'description' => 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.',
                'poster' => 'https://image.tmdb.org/t/p/w500/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg',
                'banner' => 'https://image.tmdb.org/t/p/w500/5kkw5RT1OjTAMh3P5joQfvDnBL1.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=R1v0uFms68U',
                'video_url' => '/videos/walkingdead.mp4',
                'duration' => 44,
                'release_year' => 2010,
                'quality' => 'HD',
                'age_rating' => 'T18',
                'imdb_rating' => 8.2,
                'is_series' => 1,
                'total_episodes' => 177,
                'current_episode' => 177,
                'is_featured' => 1,
                'is_latest' => 1,
                'status' => 1,
                'country_id' => 1,
                'director_id' => 1,
                'actors' => [
                    ['name' => 'Andrew Lincoln', 'slug' => 'andrew-lincoln', 'character_name' => 'Rick Grimes'],
                    ['name' => 'Norman Reedus', 'slug' => 'norman-reedus', 'character_name' => 'Daryl Dixon'],
                    ['name' => 'Danai Gurira', 'slug' => 'danai-gurira', 'character_name' => 'Michonne'],
                ],
            ],
        ];

        foreach ($movies as $movieData) {
            $actors = $movieData['actors'];
            unset($movieData['actors']);
            $movie = Movie::updateOrCreate(['slug' => $movieData['slug']], $movieData);
            foreach ($actors as $actorData) {
                $actor = Actor::firstOrCreate(
                    ['slug' => $actorData['slug']],
                    [
                        'name' => $actorData['name'],
                        'biography' => $actorData['biography'] ?? null,
                        'avatar' => $actorData['avatar'] ?? null,
                        'birth_date' => $actorData['birth_date'] ?? null,
                        'birth_place' => $actorData['birth_place'] ?? null,
                        'status' => $actorData['status'] ?? 1,
                    ]
                );
                // Gán diễn viên vào phim với tên nhân vật
                DB::table('movie_actor')->updateOrInsert([
                    'movie_id' => $movie->id,
                    'actor_id' => $actor->id
                ], [
                    'character_name' => $actorData['character_name']
                ]);
            }
        }
    }
} 